### ISSUE TITLE
completely new to github, can anyone help me compile this code?

### ISSUE THREAD

**Issue by conradikal** [Rem0o/FanControl.HWInfo#13]
I'm new to compiling and github but not to computers. I have Visual studio and the .dll files but don't know where to begin. Thanks for understanding

**Comment by northmatt** [comment]
Open `FanControl.HWInfo.sln` with VS then click `Local Windows Debugger` (in the top middle-ish of window with green arrow) which builds and attempts to run (if it can depending on what is being built) the project. 

Do note that this plugin has a bug where values can randomly be detached from HWiNFO and become arbitrary numbers. I'd recommend a custom [LibreHardwareMonitor](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor) build which has whatever you need. Look through the PRs/issues/forks to see if you can find the extra features you need. I use a custom LHM for RAM temps and it works fine.
