### ISSUE TITLE
Unable to find the specified file

### ISSUE THREAD

**Issue by darrencoen** [Rem0o/FanControl.HWInfo#14]
Placing the 4 files into the plugins directory of fan control, the log reads:

`4/5/2022 6:48:19 AM: System.IO.FileNotFoundException: Unable to find the specified file.
   at FanControl.HWInfo.HWInfo..ctor() in C:\projects\fancontrol-hwinfo\HwInfo.cs:line 38
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 18
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
4/5/2022 6:48:19 AM: HWInfo could not initialize.
4/5/2022 6:48:50 AM: System.IO.FileNotFoundException: Unable to find the specified file.
   at FanControl.HWInfo.HWInfo..ctor() in C:\projects\fancontrol-hwinfo\HwInfo.cs:line 38
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 18
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
4/5/2022 6:48:50 AM: HWInfo could not initialize.`

It doesn't occur in the log without the files in /plugins/. I don't have a c:\projects\fancontrol-hwinfo\ directory so I assume that's somehow hard coded?

**Comment by IamGimli** [comment]
I'm having the same issue. I believe that's a problem with how the plugin available on AppVeyor was compiled as those are the directories used before the plugin is compiled.

**Comment by Rem0o** [comment]
If you looked at the stacktrace a bit, which is a debug compiled version, hence the paths, you would see it doesn't find the memory mapped file, aka the Shared memory of HWInfo, meaning it's off.

**Comment by IamGimli** [comment]
Thank you for the explanation, turns out you have to restart HWInfo after enabling shared memory for it to kick in, it's working now i.e. I can see the data from HWInfo in FanControl, although strangely the sensor settings page still says there's no plugin loaded.

**Comment by Rem0o** [comment]
That's odd, mine does ?
![image](https://user-images.githubusercontent.com/14118956/162844599-04cea3b1-02e0-4d36-ad9f-584d494cdb43.png)

**Comment by IamGimli** [comment]
Yeah, it's weird, but it works, I guess.
![FanControl](https://user-images.githubusercontent.com/4108838/162845154-3d000b08-8058-4a1a-83d4-c4f81a68f18c.png)

**Comment by darrencoen** [comment]
mine also does not show

![image](https://user-images.githubusercontent.com/611705/162846247-bb49ef9e-3529-4800-a0e6-68ef2aa1f98b.png)

**Comment by darrencoen** [comment]
![image](https://user-images.githubusercontent.com/611705/162846427-ec2ac2b5-7312-4cb5-a3b7-37d9aebaf8a3.png)

**Comment by Rem0o** [comment]
Exit restart => still no plugin in the plugin section?

**Comment by darrencoen** [comment]
> Exit restart => still no plugin in the plugin section?

correct.

**Comment by Rem0o** [comment]
no logs or anything?

**Comment by darrencoen** [comment]
```
4/11/2022 3:52:27 PM: System.IO.FileNotFoundException: Unable to find the specified file.
   at FanControl.HWInfo.HWInfo..ctor() in C:\projects\fancontrol-hwinfo\HwInfo.cs:line 38
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 18
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
4/11/2022 3:52:27 PM: HWInfo could not initialize.
4/11/2022 3:54:07 PM: System.IO.FileNotFoundException: Unable to find the specified file.
   at FanControl.HWInfo.HWInfo..ctor() in C:\projects\fancontrol-hwinfo\HwInfo.cs:line 38
   at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 18
   at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
4/11/2022 3:54:07 PM: HWInfo could not initialize.```

**Comment by Rem0o** [comment]
I'm out of ideas, no clue as to how it's not displayed if the backend provider is initialized and sensors are shown.

**Comment by Rem0o** [comment]
New idea:

Tick or untick any checkbox in that sensorsetting menu, click ok, then come back. Is the plugin now visible?

**Comment by darrencoen** [comment]
so, i dunno if this helps or matters but for the record:

1. i completely gutted the fan control directory of any and all files and logs except the updater (which downloads everything clean)
2. the plugins directory was also untouched containing your plugin
3. hwinfo was running 
4. loading a completely fresh fan control, again it shows no plugin but it actually creates no errors

it is only when hwinfo is not running that it produces the errors i've posted and fails to initialize.

so this ghost plugin-loaded thing is maybe a fan control problem and not any issue of yours?

**Comment by darrencoen** [comment]
> New idea:
> 
> Tick or untick any checkbox in that sensorsetting menu, click ok, then come back. Is the plugin now visible?

![image](https://user-images.githubusercontent.com/611705/162848047-f3a4eb6d-42bb-49c7-8cf2-350f21b66854.png)

responded "no"

![image](https://user-images.githubusercontent.com/611705/162848077-2642c709-99c3-444f-9cfc-9be3756e1e00.png)

sensor settings first look

![image](https://user-images.githubusercontent.com/611705/162848163-036fdce2-c360-4556-8ed4-baf8b89426d4.png)

unchecking all about to hit ok...

![image](https://user-images.githubusercontent.com/611705/162848192-ba14e9d1-1e02-4a84-ae31-28ee61dec272.png)

yes

![image](https://user-images.githubusercontent.com/611705/162848215-b4793511-8d02-4eb4-ac96-65c2d883a406.png)

errors galore

![image](https://user-images.githubusercontent.com/611705/162848234-43add5e7-9082-4fb5-9a98-9e39df8a0fc1.png)

progress?

**Comment by Rem0o** [comment]
Yes.   You had to make a change to the sensor settings for the plugin text to be loaded in.  I got the bug figured out.

**Comment by Turranius** [comment]
> ```
> 4/11/2022 3:52:27 PM: System.IO.FileNotFoundException: Unable to find the specified file.
>    at FanControl.HWInfo.HWInfo..ctor() in C:\projects\fancontrol-hwinfo\HwInfo.cs:line 38
>    at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 18
>    at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
> 4/11/2022 3:52:27 PM: HWInfo could not initialize.
> 4/11/2022 3:54:07 PM: System.IO.FileNotFoundException: Unable to find the specified file.
>    at FanControl.HWInfo.HWInfo..ctor() in C:\projects\fancontrol-hwinfo\HwInfo.cs:line 38
>    at FanControl.HWInfo.HWInfoPlugin.Initialize() in C:\projects\fancontrol-hwinfo\HWInfoPlugin.cs:line 18
>    at FanControl.Domain.BackendProviders.Plugin.PluginBackendProvider.Open()
> 4/11/2022 3:54:07 PM: HWInfo could not initialize.```
> ```

Exactly the same problem for me. It does show up just fine but refuses to load.

**Comment by Rem0o** [comment]
> Unable to find the specified file.

Shared memory is not turned on or HWInfo is not on.

**Comment by Turranius** [comment]
Thanks.

It was on and shared but I figured I needed to open the sensors window in HWInfo as well. Then it stopped complaining. It popped up a few new fans with new names but no new temprature sources for us in the graph curves. Weird.

Anyway, I'm happy without memory temperature. Would have been nice to toss into a mixed graph as they get warm as heck on a 3080Ti =)
