### ISSUE TITLE
Still cannot work when HWInfo setting to Chinese or Japanese

### ISSUE THREAD

**Issue by abcdehc** [Rem0o/FanControl.HWInfo#50]
with newest version of FanControl, HWInfo, and Plugin.
it is because the Character Encoding.
details in #47

**Comment by abcdehc** [comment]
#47

**Comment by ouyangyiluo** [comment]
Try this version https://github.com/Rem0o/FanControl.HWInfo/commit/c166d1467555ae702e0b979143c711835ef6643e

**Comment by abcdehc** [comment]
> Try this version [c166d14](https://github.com/Rem0o/FanControl.HWInfo/commit/c166d1467555ae702e0b979143c711835ef6643e)

I didn't know how to compile the solution, could you please help me about it? Or waiting release in this project... but it's seems that the creater is lazy in this project

**Comment by Rem0o** [comment]
https://ci.appveyor.com/project/Rem0o/fancontrol-hwinfo/build/artifacts
