### ISSUE TITLE
Plugin does not work on version 94 of FanControl

### ISSUE THREAD

**Issue by dnlrf** [Rem0o/FanControl.HWInfo#8]
I have not tried using it on previous versions. When I open the list of sensors in the graph box, only the default sensors are available. Is there a way to enable the plugin?

Below I have attached screenshots of the plugin folder and my hwinfo settings in case I did anything wrong.

Edit: I'm using v6.42 of hwinfo, without the shared memory limiter.

![Screenshot 2021-10-14 172351](https://user-images.githubusercontent.com/23234663/137413128-c56bac31-a4d8-45f5-8d3b-3cf58bd72994.png)
![Screenshot 2021-10-14 172322](https://user-images.githubusercontent.com/23234663/137413131-50bf43d5-7e82-4e73-bf69-ba69b367ef77.png)

**Comment by user2am** [comment]
I have the same problem. I can't get Fan Control to recognize the HWiNFO64 Plugin.
I am not sure what you mean by "sensor read mode". 

I only downloaded the four files and copied them into the Plugins Folder, as seen in the second screenshot. Do I have to edit the files in any way?
Do I have to use the files from FanControl.HWInfo as well?

Thank you for your time!

**Comment by Rem0o** [comment]
@user2am 
![image](https://user-images.githubusercontent.com/14118956/146809338-004bd362-d8a5-414f-a0af-17400c0a9f7a.png)

**Comment by user2am** [comment]
Okay, that is what I am using.

Do we have to use your files? I only downloaded the four files from AppVeyor, as explained in the README.md. I did not use any of the files of this repo (e.g. "FanControl.HWInfo.csproj"). Maybe I am misunderstanding the installation guide?

**Comment by Rem0o** [comment]
Make sure all the plugin dlls are unlocked.   Right-click => properties.
Make sure HWInfo is running b4 FanControl.

**Comment by user2am** [comment]
Unlocking the dlls worked! I would have never thought of this. Thank you so much!
