### ISSUE TITLE
No binary available

### ISSUE THREAD

**Issue by GittyBaer** [Rem0o/FanControl.HWInfo#9]
Hi Rem0o,
not an real issue:
But there is no binary available anymore:
appveyor.com has deketed the artifact, because it was to old.

Can you please make a binary available again. Thx!

**Comment by Whitedoteu** [comment]
https://ci.appveyor.com/project/Whitedoteu/fancontrol-hwinfo/build/artifacts
Temp fix

**Comment by Hxd097** [comment]
> https://ci.appveyor.com/project/Whitedoteu/fancontrol-hwinfo/build/artifacts Temp fix

Can you compile this again pls
I've been trying for an hour but nothing works

**Comment by djruess** [comment]
> > https://ci.appveyor.com/project/Whitedoteu/fancontrol-hwinfo/build/artifacts Temp fix
> 
> Can you compile this again pls I've been trying for an hour but nothing works

Same!

**Comment by Rem0o** [comment]
Re started the build.

**Comment by Whitedoteu** [comment]
@Rem0o So we can closed this?
